# Usa una imagen base de Python
FROM python:3.12

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo de requerimientos al contenedor
COPY requirements.txt requirements.txt

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el archivo main.py al contenedor
COPY main.py main.py

# Copia el archivo pipeline.conf al contenedor
COPY pipeline.conf pipeline.conf

# Copia las carpetas bronze y silver al contenedor
COPY ..data/bronze data/bronze
COPY ..data/silver data/silver

# Comando para ejecutar el servicio de Prefect y el script de transformaciones
CMD ["sh", "-c", "prefect orion start & python main.py"]